filebeat.inputs:
- type: log
  paths:
    - /var/log/dsiem/siem_alarm_events.json
  fields_under_root: true
  fields: { application: siem, siem_data_type: alarm_events }
  tail_files: true
  json.keys_under_root: true
  json.overwrite_keys: true

- type: log
  paths:
    - /var/log/dsiem/siem_alarms.json
  fields_under_root: true
  fields: { application: siem, siem_data_type: alarms }
  tail_files: true
  json.keys_under_root: true
  json.overwrite_keys: true

- type: log
  paths:
    - /var/log/dsiem/dtester.json
  fields_under_root: true
  fields: { application: dtester }
  tail_files: true
  json.keys_under_root: true
  json.overwrite_keys: true

- type: log
  paths:
    - "/var/log/digital_twin/*.log"
  fields_under_root: true
  fields: { application: digital_twin }

output:
 logstash:
   hosts: ["logstash:5001"]
